name: Run Scraper

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python chuni_rating.py

      - name: Upload Playwright Trace
        if: always()  # Upload the trace even if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: trace.zip
